// <auto-generated />
using System;
using BTL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTL.Migrations
{
    [DbContext(typeof(EntityModel))]
    partial class EntityModelModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BTL.Models.Audio", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AudioSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Audios");
                });

            modelBuilder.Entity("BTL.Models.AudioDate", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AudioID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DateID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("AudioID");

                    b.HasIndex("DateID");

                    b.ToTable("AudioDates");
                });

            modelBuilder.Entity("BTL.Models.DateControl", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Controls");
                });

            modelBuilder.Entity("BTL.Models.AudioDate", b =>
                {
                    b.HasOne("BTL.Models.Audio", "Audio")
                        .WithMany("AudioDates")
                        .HasForeignKey("AudioID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BTL.Models.DateControl", "Date")
                        .WithMany("AudioDates")
                        .HasForeignKey("DateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audio");

                    b.Navigation("Date");
                });

            modelBuilder.Entity("BTL.Models.Audio", b =>
                {
                    b.Navigation("AudioDates");
                });

            modelBuilder.Entity("BTL.Models.DateControl", b =>
                {
                    b.Navigation("AudioDates");
                });
#pragma warning restore 612, 618
        }
    }
}
