version: '3.0.8'

services:
  music_data:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: music_data
    environment:
      MSSQL_SA_PASSWORD: "Password789"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql

  music_studio:
    image: hungvu034/musicstudio:latest
    ports:
      - 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=Data Source=music_data,1433;Initial Catalog=MusicStudio;User ID=SA;Password=Password789;
volumes:
  mssql_data:
    name: mssql_data
